---
- name: Include automatic updates tasks
  ansible.builtin.include_tasks: updates.yml
  tags: [updates]
  when: baseline_unattended_upgrades_enabled

- name: Include SSH hardening tasks
  ansible.builtin.include_tasks: ssh.yml
  tags: [ssh]

- name: Include firewall tasks
  ansible.builtin.include_tasks: firewall.yml
  tags: [firewall]

- name: Include sysctl hardening tasks
  ansible.builtin.include_tasks: sysctl.yml
  tags: [sysctl]

- name: Include MOTD tasks
  ansible.builtin.include_tasks: motd.yml
  tags: [motd]
