---
# NTP
baseline_ntp_package: chrony
baseline_ntp_service: chrony
baseline_ntp_servers:
  - 0.nl.pool.ntp.org
  - 1.nl.pool.ntp.org
  - 2.nl.pool.ntp.org
  - 3.nl.pool.ntp.org

# SSH Hardening
baseline_ssh_port: 22
baseline_ssh_permit_root_login: "prohibit-password"
baseline_ssh_password_authentication: "no"
baseline_ssh_max_auth_tries: 3
baseline_ssh_x11_forwarding: "no"

# Firewall (UFW)
baseline_firewall_enabled: true
baseline_firewall_default_incoming: deny
baseline_firewall_default_outgoing: allow
baseline_firewall_allowed_ports:
  - {port: "{{ baseline_ssh_port }}", proto: tcp, comment: "SSH"}

# MOTD
baseline_motd_message: "Beheerd door Ansible via Semaphore"
baseline_motd_contact: "infra@example.com"
